### ISSUE TITLE
Adicionar Rust em Tecnologias 

### ISSUE THREAD

**Issue by developerfred** [leticiadasilva/por-onde-comecar#1]
Adicionar em tecnologia o arquivo `Rust.md` e adicionar uma lista de conteúdos em português do Brasil 

Exemplo: [Iniciando com Rust - Mozilla ](https://developer.mozilla.org/pt-BR/docs/Mozilla/Rust)

**Comment by leticiadasilva** [comment]
Adicionado! (https://github.com/leticiadasilva/por-onde-comecar/blob/master/Tecnologias/Rust/rust.md)

Valeu pela dica!
