### ISSUE TITLE
Criar conteúdos iniciantes de Solidity 

### ISSUE THREAD

**Issue by Lorenzobattistela** [leticiadasilva/por-onde-comecar#121]
Adicionar repositório contendo conteúdos iniciantes de Solidity, linguagem utilizada no desenvolvimento blockchain, principalmente Ethereum. É uma área com bastante demanda e muito legal de aprender.

**Comment by leticiadasilva** [comment]
Adorei a ideia, Lorenzo! Já aceitei teu PR <3
